development/core/urls.py
# django core
from django.conf.urls import patterns, include, url

# 3rd party apps
from haystack.forms import ModelSearchForm

# mfb imports
from .formscoresearch import CoreAutoCompleteForm
from .viewscoresearch import autocompleteSearch

urlpatterns = patterns('',
	url(r'^$', 'core.viewscoresearch.autocompleteSearch', name='acsearch'),
)

development/blog/models.py
# stdlib imports

# core django imports
from django.db import models
#from django.contrib.auth.models import User

# 3rd party app imports

# project's imports


class Entry(models.Model):
	title				= models.CharField(max_length=500)
	#author				= models.ForeignKey('auth.User')
	body				= models.TextField()
	created_at			= models.DateTimeField(auto_now_add=True, editable=False)
	modified_at			= models.DateTimeField(auto_now=True)
	event_date			= models.DateField(null=True)
	#event_end_date		= models.DateTimeField(null=True)
	#slug			= models.SlugField()


	class Meta:
		verbose_name_plural = "entries"
		ordering = ["-event_date","-title"]

	def __unicode__(self):
		return self.title

	def get_event_date(self):
		return self.event_date.strftime("%A, %B %d, %Y")

development/templates/accounts/admin_settings.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
**accounts/admin_settings.html**
customized submission form that allows user to
upload a scene file or a file of a given format
to the MFB server
{% endcomment %}

{% block admin_settings_form %}
<h3 class="dashboard-headings" style="margin-left:0px">My Admin Settings</h3>
	<div class="control-group">
	<div class="controls">
		<!--<span for="id_username">Username: </span>{{ username }}<br /><br />-->
		<div class="btn-group">
			<a href="{% url 'post_tutorial' %}" ><button type="button" class="btn btn-sm" id="anchor_edit_password">Post a Tutorial</button></a><br /><br />
			<a href="{% url 'feature_tutorial_change' %}" ><button type="button" class="btn btn-sm" id="anchor_edit_email">Change Feature Tutorial</button></a><br /><br />
			<a href="{% url 'feature_animation_change' %}" ><button type="button" class="btn btn-sm" id="anchor_edit_email">Change Feature Animation</button></a><br /><br />
			<a href="{% url 'feature_animation_change' %}" ><button type="button" class="btn btn-sm" id="anchor_edit_email">Change Staff Picks</button></a><br /><br />
			<a href="{% url 'post_news' %}" ><button type="button" class="btn btn-sm" id="anchor_edit_password">Post a News Event</button></a><br /><br />
			<a href="{% url 'modify_news' %}" ><button type="button" class="btn btn-sm" id="anchor_edit_password">Modify a News Event</button></a><br /><br />

		</div>
	</div>
	</div>
<script type="text/javascript">
  $(document).ready(function(){
	$('#id_username').css("visibility","hidden");
	$('#id_password').css("visibility","hidden");
	$('#id_first_name').prop("placeholder","Enter your first name");
	$('#id_last_name').prop("placeholder","Enter your last name");
	$('#id_email').prop("placeholder","Enter a current email address");
	if ( $('.errorlist').length ) {
	  $('input[id=id_email]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
		//$(this).siblings().eq(0).remove();
	  });
	}
	if ( $('input[id=id_email]').val() === "" ) {
	  $('input[id=id_email]').before('<span style="color:red;font-size:small">This field is required.</span><br />');
	}
  });
</script>
{% endblock %}

development/templates/accounts/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	{% if user.is_authenticated %}
		<h2 class="dashboard-headings span12"><img {% if user.userpic %} src="{{ user.userpic }}"  {% else %} src="{% static 'img/avatar_user_50x50.png' %}" {% endif %} alt={{ user.username }} /> {{ user.username }}'s Bookshelf</h2>
	{% endif %}	
		<div class="span3 pull-left" style="margin-left:-20px" >
		{% if user.is_staff %}
			<ul class="nav nav-pills nav-stacked">
				<li><a href="{% url 'dashboard' %}" class="uploads-user"><i class="icon-home"></i> My Dashboard</a></li>
				<li><a href="{% url 'upload' %}" class="uploads-user"><i class="icon-upload"></i> Upload</a></li>
				<li><a href="{% url 'uploadsmanager' %}" class="uploads-user"><i class="icon-facetime-video"></i> Uploads Manager</a></li>
				<li><a href="{% url 'user_settings' %}"><i class="icon-cog"></i> Settings</a></li>
				<li><a href="{% url 'admin_settings' %}"><i class="fa fa-vimeo-square"></i> Admin Utilities</a></li>				
			</ul>
		{% else %}
			<ul class="nav nav-pills nav-stacked">
				<li><a href="{% url 'dashboard' %}" class="uploads-user"><i class="icon-home"></i> My Dashboard</a></li>
				<li><a href="{% url 'upload' %}" class="uploads-user"><i class="icon-upload"></i> Upload</a></li>
				<li><a href="{% url 'uploadsmanager' %}" class="uploads-user"><i class="icon-facetime-video"></i> Uploads Manager</a></li>
				<li><a href="{% url 'user_settings' %}"><i class="icon-cog"></i> Settings</a></li>
			</ul>
		{% endif %}
		</div> <!-- span2 -->
		
		<div class="span9"> 
			{% block uploadsmanager %}
			{% endblock %}

			{% block successfulupload %}
			{% endblock %}
			
			{% block dashboard-master %}
			{% endblock %}
			
			{% block submission-form %}
			{% endblock %}
			
			{% block revision-form %}
			{% endblock %}
			
			{% block revision-success %}
			{% endblock %}
			
			{% block revision-info %}
			{% endblock %}

			{% block rev_tagging %}
			{% endblock %}

			{% block user_settings_form %}
			{% endblock %}

			{% block change_password_form %}
			{% endblock %}

			{% block change_password_done %}
			{% endblock %}

			{% block address_change_form %}
			{% endblock %}

			{% block address_change_done %}
			{% endblock %}

			{% block email_change_form %}
			{% endblock %}

			{% block email_change_done %}
			{% endblock %}

			{% block admin_settings_form %}
			{% endblock %}

			{% block post_tutorial_form %}
			{% endblock %}

			{% block post_tutorial_done %}
			{% endblock %}

			{% block post_news_form %}
			{% endblock %}

			{% block feature_tutorial_change_form %}
			{% endblock %}

			{% block feature_tutorial_change_done %}
			{% endblock %}
		</div>  <!-- info content -->
{% endblock %}

development/templates/accounts/feature_tutorial_change_done.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
Redirect changing feature tutorial upon success.
{% endcomment %}

{% block title %}Feature tutorial change successful{% endblock %}

{% block feature_tutorial_change_done %}
<section class="successful_upload_msg">
	<h1 class="dashboard-headings">Super!</h1>
		<p>
		{{ username }}, your featured tutorial <a href="{% url 'tutinfo' tutPk=tutpk %}">{{ title }}</a> has been saved.<br /><br />

		<br />
		</p>
		<br /><br />
</section>
{% endblock %}

development/templates/accounts/feature_tutorial_change_form.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
**accounts/feature_tutorial_change_form.html**
customized submission form that allows user to
upload a scene file or a file of a given format
to the MFB server
{% endcomment %}

{% block title %}Feature Tutorial Change{% endblock %}

{% block feature_tutorial_change_form %}
<h3 class="dashboard-headings" style="margin-left:0px">My Admin Settings: Change Feature Tutorial</h3>
	{% if tuts %}
		<p id="pw_info">Administrators: Presently, only one tutorial can be the featured tutorial.<br /><br /></p>
		<form id="user_form" action="" method="post">{% csrf_token %}
			<div class="control-group">
			<div class="controls">
				<span for="id_old_password">Current password:</span><br />
				{% if form.old_password.errors %}<p class="error">{{ form.old_password.errors }}</p>{% endif %}
				{{ form.old_password }}<br/>
			</div>
			</div>
			<div class="control-group">
			<div class="controls">
				<span for="id_new_password1">New password:</span><br />
				{% if form.new_password1.errors %}<p class="error">{{ form.new_password1.errors }}</p>{% endif %}
				{{ form.new_password1 }}<br/>
			</div>
			</div>
			<div class="control-group">
			<div class="controls">
				<span for="id_new_password2">Confirm password:</span><br />
				{% if form.new_password2.errors %}<p class="error">{{ form.new_password2.errors }}</p>{% endif %}
				{{ form.new_password2 }}<br/>
			</div>
			</div>
			<div class="control-group" >
			<div class="controls" align=left>
				<input id="confirm_pw_2x_submit" type="submit" class="big bg-color-greenLight" style="color:#3CA83C" alt="Change Password Form" value="Save Change" />
				<br/><br/>
			</div>
			</div>
		</form>
		<h3 class="dashboard-headings" style="margin-left:0px">List of Tutorials by ID and Title</h3>
		<p>Select a tutorial's title as the new featured tutorial</p>
		{% for tut in tuts %}
			<form id="feature_tut_form" action="" method="post">{% csrf_token %}
			<a href="">[Vimeo ID {{ tut.vimeoid }}</a>] {{ tut.title }}: <br />
					{% if tutform.tutfeature.errors %}<p class="error">{{ tutform.tutfeature.errors }}</p>{% endif %}
					<label id="feature_label">*Featured Tutorial? {{ tutform.tutfeature }} </label>
					<span><input id="confirm_pw_2x_submit" type="submit" class="big bg-color-greenLight" style="color:#3CA83C" alt="Change Password Form" value="Save Change" /></span><br />
			</form>
		{% endfor %}
		<br />
	{% else %}
		<p>Administrators: There are currently no tutorials posted. Please <a href="{% url 'post_tutorial' %}">post a tutorial</a>.</p> 
	{% endif %}
<script type="text/javascript">
  $(document).ready(function(){
	if ( $('.errorlist').length ) {
	  $('input[id=id_old_password]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
	  });
	  $('input[id=id_new_password1]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
	  });
	  $('input[id=id_new_password2]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
	  });
	}
  });
</script>
{% endblock %}

development/templates/accounts/post_news_form.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
**accounts/post_news_form.html**
customized submission form that allows user to
upload a scene file or a file of a given format
to the MFB server
{% endcomment %}

{% block post_news_form %}
<h3 class="dashboard-headings" style="margin-left:0px">My Admin Settings: Post a News Entry</h3>
Administrators: To post a news entry on the <a href="{% url 'news' %}">News page</a>, please fill out the form below.<br /><br /> 
To modify a posted news entry, click <a href="{% url 'modify_news' %}">Modify News Entry</a>.<br /><br />
<form id="news_form" action="{% url 'post_news' %}" method="post">{% csrf_token %}

	<div class="control-group">
	<div class="controls">
		{% if entryform.event_date.errors %}<p class="error">{{ entryform.event_date.errors }}</p>{% endif %}
		{{ entryform.event_date }} 
	</div>
	</div>
	<div class="control-group">
	<div class="controls">
		{% if entryform.title.errors %}<p class="error">{{ entryform.title.errors }}</p>{% endif %}
		{{ entryform.title }}<br />
	</div>
	</div>
	<div class="control-group">
	<div class="controls">
		{% if entryform.body.errors %}<p class="error">{{ entryform.body.errors }}</p>{% endif %}
		{{ entryform.body }}<br />
	</div>
	</div>
	<div class="control-group" >
	<div class="controls" align=left>
		<input type="submit" name="post_news" alt="Settings Form" style="color:#3CA83C" value="Post News Event" />
		<br /><br />
	</div>
	</div>

</form>
<script type="text/javascript">
  $(document).ready(function(){
  	$( "#id_event_date" ).datepicker({ dateFormat: 'yy-mm-dd' });

	if ( $('.errorlist').length ) {
	  $('input[id=id_event_date]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
	  });
	}

	if ( $('.errorlist').length ) {
	  $('input[id=id_title]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
	  });
	}

	if ( $('.errorlist').length ) {
	  $('input[id=id_body]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
	  });
	}
  });
</script>
{% endblock %}

development/templates/accounts/post_tutorial_done.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
Redirect tutorial posting upon success.
{% endcomment %}

{% block post_tutorial_done %}
<section class="successful_upload_msg">
	<h3 class="dashboard-headings">Administrators are awesome, aren't we?!</h3>
		<p>
		Check the <a href="{% url 'tutorial' %}">Tutorial</a> library for your posted <a href="{% url 'tutinfo' tutPk=tutpk %}">Vimeo tutorial #{{ vimeoid }}.</a><br />
		</p>
		<br /><br />
</section>
{% endblock %}

development/templates/accounts/post_tutorial_form.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
**accounts/post_tutorial_form.html**
customized submission form that allows user to
upload a scene file or a file of a given format
to the MFB server
{% endcomment %}

{% block post_tutorial_form %}
<h3 class="dashboard-headings" style="margin-left:0px">My Admin Settings: Post a Tutorial</h3>
Administrators: To post a tutorial for display in the <a href="{% url 'tutorial' %}">Tutorials page</a>, please enter a valid Vimeo ID in the form below.<br /><br /> 
<strong>*Note</strong> : Only <i>one</i> tutorial can be a featured tutorial. If the checkbox is disabled, a tutorial feature has already been chosen. Otherwise, click on the checkbox to pick this tutorial as the featured tutorial and click the button "Post Tutorial". <br /><br />
To select another tutorial as the featured one, click <a href="{% url 'feature_tutorial_change' %}">Change Feature Tutorial</a>.<br /><br />
<form id="tutorial_form" action="{% url 'post_tutorial' %}" method="post">{% csrf_token %}
	<div class="control-group">
	<div class="controls">
		{% if tutform.vimeoid.errors %}<p class="error">{{ tutform.vimeoid.errors }}</p>{% endif %}
		{{ tutform.vimeoid }}<br />
	</div>
	</div>
	<div class="control-group">
	<div class="controls">
		{% if tutform.comments.errors %}<p class="error">{{ tutform.comments.errors }}</p>{% endif %}
		{{ tutform.comments }}<br />
	</div>
	</div>
	<div class="control-group">
	<div class="controls" id="checkbox_div">
		{% if tutform.tutfeature.errors %}<p class="error">{{ tutform.tutfeature.errors }}</p>{% endif %}
		<label id="feature_label">*Featured Tutorial? {{ tutform.tutfeature }}</label><br />
	</div>
	</div>
	<div class="control-group" >
	<div class="controls" align=left>
		<input type="submit" name="post_tutorial" alt="Settings Form" style="color:#3CA83C" value="Post Tutorial" />
		<br /><br />
	</div>
	</div>
</form>
<script type="text/javascript">
  $(document).ready(function(){
	if ( $('.errorlist').length ) {
	  $('input[id=id_vimeoid]').on('focus',function() {
		$('.error').remove();
		$('.errorlist').remove();
	  });
	}
	if ( {{ tutblocked }} === true ) {
		$('input[id=id_tutfeature]').prop('disabled',true).addClass('read-only');
		$('input[id=id_tutfeature]').on('click', function(e){
		  e.preventDefault();
		});
	}
	else if ( {{ tutblocked }} === false ) {
		$('input[id=id_tutfeature]').removeProp('disabled',false).removeClass('read-only');
	}
  });
</script>
{% endblock %}

development/templates/accounts/revision_success.html
{% extends "accounts/dashboard.html" %}

{% comment %}
**URL Design: profile/revise/(?P<pkVid>(\d+))/$**
After successful submission of a 
revision of a Submission object, display
detailed information for the object and 
and its history
{% endcomment %}

{% block revision-success %}
<section class="rev-success-container">
	<h2>Updated Revision Details</h2>
	
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	<section class=" rev-video-content">
		<div class="rev-video">
			<img src="{{ new_revision.thumb_large }}" alt="{{ title }}" /><br /><br />
			<a href="" >new revision video player here </a>
		</div>
		<div class="rev-video-title">
			<h4>{{ title }}</h4> <br />
			<input id="title_entry" style="display:none;"></input>
			PDBs: <span id="pdb">{{ pdbs }}</span><br />
			<input id="pdb_entry" style="display:none;"></input>
		</div>
		<div class="rev-userprofile-img">
		UserProfile Image here<br />
		</div>
		<div class="rev-userprofile-name">
			Username: {{ username }} <span class="small">{{ vidCount }} videos</span><br /><br />
			<button>Subscribe</button>
			
		</div>
		<div class="rev-viewcount">
		Number of View
		
		</div>
		<div class="vm-date-timestamp-info">
		Uploaded on {{ latestRev }}
		</div>
		<div class="vm-video-info">
			Description: {{ description }} <br />
		</div>
		<section class="ac-container">
		<strong>Tags: </strong>{{ tags }}<br />
		Comments: {{ comments }}
		</section>
		<br /><br />
	</section>
</section>

<script type="text/javascript">
$(document).ready(function(){

	$('.messages > li').delay(1000).fadeOut();
});//end ready
</script>
{% endblock %}

development/templates/accounts/successful_revision.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
Redirect submission upload and revision upload upon success.
{% endcomment %}

{% block successfulupload %}
<section class="successful_upload_msg">
	<h4 class="dashboard-headings">Awesome!</h4>
		<p>
		Your revision uploads were received.<br /><br />
		Check out <a href="{% url 'revinfo' revPk=revid %}">your new revision.</a><br />
		</p>
		<br /><br />
</section>
{% endblock %}

development/templates/accounts/successful_revtagging.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
**URL Design: templates/accounts/**
Displays list of all submissions, each 
with a revision history, that a
user has uploaded to their account.
{% endcomment %}

{% block rev_tagging %}
<section class="successful_upload_msg">
	<h1 class="dashboard-headings">Done!</h1>
		<p>
		Your tags for <a class="sublinks" href="{% url 'revinfo' revPk %}">"{{ title }}"</a> have been added.<br /><br />
		Continue browsing the <a href="{% url 'uploadsmanager' %}">Uploads Manager.</a><br />
		</p>
		<br /><br />
</section>
{% endblock %}

development/templates/accounts/successful_submission.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
Redirect submission upload and revision upload upon success.
{% endcomment %}

{% block successfulupload %}
<section class="successful_upload_msg">
	<h4 class="dashboard-headings">Awesome!</h4>
		<p>
		Your uploads and submission were received.<br /><br />
		Now go on. Check out <a href="{% url 'revinfo' revPk=revid %}">your new submission.</a><br />
		</p>
		<br /><br />
</section>
{% endblock %}

development/templates/accounts/successful_subtagging.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
Redirect tag update upon success.
{% endcomment %}

{% block content %}
<section class="successful_upload_msg">
	<h1 class="dashboard-headings"></h1>
		<p>
		Your tags for <a class="sublinks" href="{% url 'subinfo' subid revid %}">"{{ title }}"</a> have been added.<br /><br />
		Return to browsing the <a href="{% url 'library' %}">Library.</a><br />
		</p>
		<br /><br />
</section>
{% endblock %}

development/templates/accounts/uploads_manager.html
{% extends "accounts/dashboard.html" %}
{% load staticfiles %}

{% comment %}
**URL Design: templates/accounts/**
Displays list of all submissions, each 
with a revision history, that a
user has uploaded to their account.
{% endcomment %}

{% block uploadsmanager %}
<!-- <div class="container "> -->
	<div class="row">
		<h3 class="dashboard-headings" style="margin-left:15px">Uploads: {{ vidCount }}</h3>
		
		{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		
		{% for submission in submissions %}
			<div class="span2.5">
				{% for revItem in submission.revisions.all %}
					{% if forloop.last %}
					<a href="{% url 'revinfo' revPk=revItem.pk %}" title="{{ submission.title }}"><img class="side-col-thumbnail" src="{{ revItem.thumb_small }}" alt="{{ submission.title }}" /></a>
					<br /><br />
					{% endif %}
				{% endfor %}
			</div>
			
			<div class="span7">
				{% for revItem in submission.revisions.all reversed %}
					{% if forloop.first %}
						<span id="list_title"><a class="uploads-user" href="{% url 'revinfo' revPk=revItem.pk %}" title="{{ submission.title }}">{{ submission.title }}</a></span>
						<div class="btn-group">
						<a class="action-anchors btn-mini" href="{% url 'revise' pkVid=submission.pk %}" title="submit revision">Upload new version</a>
						</div><br />
					{% endif %}
				{% endfor %}
				{% for revItem in submission.revisions.all reversed %}
					{% if forloop.first %}
					<span id="list_timestamp">Timestamp: {{ revItem.modified }}</span><br />
					{% endif %}
				{% endfor %}
				<span id="list_filetype">Filetype: {{ submission.filetype }}</span><br />
				<span id="list_pdb">PDB(s): {{ submission.displayPdbs }}</span><br />
				<div class="wrapper"><div id="description_{{ submission.pk }}" style="float: none; position: static;" name="{{ submission.description }}">Description: {{ submission.description }}</div></div><br />
				<!--  this is where the history of revisions will be -->
				<button type="button" class="btn btn-small" data-toggle="collapse" data-target="#vidpk-{{ submission.pk }}">Revision History <span class="caret"></span></button>
					<div id="vidpk-{{ submission.pk}}" class="collapse out">
						<ul>
							{% for revItem in submission.revisions.all reversed %}
								<li><a class="action-anchors" href="{% url 'revinfo' revPk=revItem.pk %}" title="{{ submission.title }}">Version: {{ revItem.modified }} </a></li>
							{% endfor %}
						</ul>
					</div>
					<br />
				<br /><br />
			</div>
		{% endfor %}
	</div> <!--  end row -->
 <!-- </div> container -->

<script type="text/javascript">
	$(document).ready(function() {
		$('.wrapper').children('div').jTruncate({
			length: 200,
			minTrail: 0,
			moreText: "[read more]",
			lessText: "[read less]",
			ellipsisText: " ...",
			moreAni: "fast",
			lessAni: "fast"
		});

	}); //end doc-ready
</script>
{% endblock %}